#!/bin/bash

# Copyright 2010 Andrew De Quincey -  adq@lidskialf.net
# This file is part of rEdBus.
#
#  rEdBus is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  rEdBus is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with rEdBus.  If not, see <http://www.gnu.org/licenses/>.

. /etc/redbus.conf

INSTDIR=/usr/local/redbus

# Download stops from the website
$INSTDIR/getstops || exit 1

# Generate new stops database
$INSTDIR/makestopsdat $INSTDIR/bus2 || exit 1
cat $INSTDIR/bus2.kdt $INSTDIR/bus2.met $INSTDIR/bus2.srv > $INSTDIR/bus2.dat
/bin/gzip -n -f -9 $INSTDIR/bus2.dat || exit 1
newsum=`/usr/bin/md5sum $INSTDIR/bus2.dat.gz | cut -f1 -d ' '` || exit 1

# handle old data
if [ ! -f $INSTDIR/bus2.dat.gz.old ]; then
	echo "Old data file is missing!"
	exit 1
fi
oldsum=`/usr/bin/md5sum $INSTDIR/bus2.dat.gz.old | cut -f1 -d ' '` || exit 1
rm -f $INSTDIR/bus2.dat.gz.old
cp -f $INSTDIR/bus2.dat.gz $INSTDIR/bus2.dat.gz.old

# Publish if something has changed!
if [ x$oldsum != x$newsum ]; then
	OUTFILE=bus2.dat-`date +%s`.gz
	mv $INSTDIR/bus2.dat.gz $INSTDIR/$OUTFILE
	$INSTDIR/googlecode_upload.py -s "new bus data for `date`" -p redbus -u $GCODE_USER -w $GCODE_PASS $INSTDIR/$OUTFILE || exit 1
	rm -f $OUTFILE
else
	# Otherwise, no changed => delete the duplicated data from the database
	$INSTDIR/removedata LATEST
fi
