#!/bin/bash

# Copyright 2010, 2011 Andrew De Quincey -  adq@lidskialf.net
# This file is part of rEdBus.
#
#  rEdBus is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  rEdBus is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with rEdBus.  If not, see <http://www.gnu.org/licenses/>.

#. /etc/redbus.conf

INSTDIR=/usr/local/redbus
INSTDIR=.

nowdate=`date +%Y-%m-%dT%H:%M:%S`
dataformat=bus3

# Download data from remote sites
$INSTDIR/getlrtdata $nowdate || exit 1

# Extract stops from XML
$INSTDIR/getnaptandata $INSTDIR/stopdata/NaPTAN620.xml $nowdate || exit 1
$INSTDIR/getnaptandata $INSTDIR/stopdata/NaPTAN627.xml $nowdate || exit 1
$INSTDIR/getnaptandata $INSTDIR/stopdata/NaPTAN628.xml $nowdate || exit 1

# Generate new stops database
$INSTDIR/makestopsdat $INSTDIR/$dataformat $nowdate || exit 1
cat $INSTDIR/$dataformat.tree $INSTDIR/$dataformat.services $INSTDIR/$dataformat.stopnames > $INSTDIR/$dataformat.dat
/bin/gzip -n -f -9 $INSTDIR/$dataformat.dat || exit 1
newsum=`/usr/bin/md5sum $INSTDIR/$dataformat.dat.gz | cut -f1 -d ' '` || exit 1

# handle old data
if [ ! -f $INSTDIR/$dataformat.dat.gz.old ]; then
	echo "Old data file is missing!"
	exit 1
fi
oldsum=`/usr/bin/md5sum $INSTDIR/$dataformat.dat.gz.old | cut -f1 -d ' '` || exit 1
rm -f $INSTDIR/$dataformat.dat.gz.old
cp -f $INSTDIR/$dataformat.dat.gz $INSTDIR/$dataformat.dat.gz.old

exit 0 # HACK

# Publish if something has changed!
if [ x$oldsum != x$newsum ]; then
	OUTFILE=$dataformat.dat-`date +%s`.gz
	mv $INSTDIR/$dataformat.dat.gz $INSTDIR/$OUTFILE
	$INSTDIR/googlecode_upload.py -s "new bus data for `date`" -p redbus -u $GCODE_USER -w $GCODE_PASS $INSTDIR/$OUTFILE || exit 1
	rm -f $OUTFILE
else
	# Otherwise, no changed => delete the duplicated data from the database
	$INSTDIR/removedata LATEST
fi
