#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

# Copyright 2010 Andrew De Quincey -  adq@lidskialf.net
# This file is part of rEdBus.
#
#  rEdBus is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  rEdBus is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with rEdBus.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
import mechanize
import BeautifulSoup
import datetime
import psycopg2
import time
import xml.sax
from BusSaxDocumentHandler import BusSaxDocumentHandler

debug = False

nowdate = datetime.datetime.today()

browser = mechanize.Browser()
browser.set_handle_robots(False)
browser.add_headers = []

# grab the list of all bus services
services = {}
soup = BeautifulSoup.BeautifulSoup(browser.open('http://www.mybustracker.co.uk/index.php?display=Service').read())
service_select = soup.find("select", {"name":"serviceService"})
for option in service_select.findAll("option"):
    serviceName = option["value"].split('|')[0].strip();
    services[serviceName] = { 'ServiceName': serviceName }

if debug:
    print >>sys.stderr, "Found %i services" % len(services)

# Now grab the stop details for each
stops = {}
count = 0
for service in services:
    count += 1
    if debug:
        print >>sys.stderr, "Processing service \"%s\" (%i/%i)" % (service, count, len(services))
    
    xmlString = browser.open('http://www.mybustracker.co.uk/getServicePoints.php?serviceMnemo=%s' % service).read()
    handler = BusSaxDocumentHandler(services, stops)
    xml.sax.parseString(xmlString, handler)

# Connect to database
db = psycopg2.connect("host=beyond dbname=redbus user=redbus password=password")
dbcur = db.cursor()

# Add services to the database
for service in services.values():
    dbcur.execute("INSERT INTO services (service_name, created_date) VALUES (%s, %s); SELECT last_value FROM services_service_id_seq", 
                  (service['ServiceName'], nowdate))
    service['DbServiceId'] = dbcur.fetchone()[0]
db.commit()

# Add stops to the database
for stop in stops.values():
    dbcur.execute("INSERT INTO stops (stop_code, stop_name, x, y, created_date) VALUES (%s, %s, %s, %s, %s); SELECT last_value FROM stops_stop_id_seq", 
                  (stop['StopCode'], stop['StopName'], stop['X'], stop['Y'], nowdate))
    stop['DbStopId'] = dbcur.fetchone()[0]
    db.commit()

# Finally, populate the link table between services and stops
for stop in stops.values():
    for serviceName in stop['Services']:
        if services.has_key(serviceName):
            service = services[serviceName]
            dbcur.execute("INSERT INTO stops_services (stop_id, service_id, created_date) VALUES (%s, %s, %s)", 
                          (stop['DbStopId'], service['DbServiceId'], nowdate))
    db.commit()

# DONE
dbcur.close()
db.close()
