#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2010 Colin Paton - cozzarp@googlemail.com
# Copyright 2010 Andrew De Quincey -  adq@lidskialf.net
# This file is part of rEdBus.
#
#  rEdBus is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  rEdBus is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with rEdBus.  If not, see <http://www.gnu.org/licenses/>.

import psycopg2
from kdtree import *
import struct,os
import sys

if len(sys.argv) != 2:
  print >>sys.stderr, "Syntax: makestopsdat <destination file prefix>"
  sys.exit(1)

# Connect to database
db = psycopg2.connect("host=beyond dbname=redbus user=redbus password=password")
curs = db.cursor()
mapcurs = db.cursor()

# Use only the latest data
curs.execute("SELECT max(created_date) FROM services")
latestdate = curs.fetchone()[0]

# Get the list of services from the database
servicesById = {}
servicesList = []
curs.execute("SELECT service_id, service_name FROM services WHERE created_date = %s ORDER BY service_name", (latestdate, ))
for row in curs:
    dbserviceid = row[0]
    service_name  = row[1]
    service = { 'DbServiceId' : dbserviceid, 
                'ServiceName' : service_name,
                'ServiceIdx'  : len(servicesList) 
              };             
    servicesById[dbserviceid] = service
    servicesList.append(service);
if len(servicesList) > 64:
    print >>sys.stderr, "Error: more than 64 services found - need to fix file format!"
    sys.exit(1)

# Get the list of stops from the database
stops=[]
curs.execute("SELECT stop_id, stop_code, stop_name, x, y FROM stops WHERE created_date = %s order by stop_code desc", (latestdate, ))
for row in curs:
    # stop data
    dbstopid = row[0]
    code = row[1]
    name = row[2]
    x = float(row[3])
    y = float(row[4])

    stopmap = 0
    mapcurs.execute("SELECT service_id FROM stops_services WHERE created_date = %s AND stop_id = %s", (latestdate, dbstopid))
    for maprow in mapcurs:
        service = servicesById[maprow[0]]
        stopmap |= 1 << service['ServiceIdx']

    stops.append(((x,y),code,name,0,stopmap))
if len(stops) > 32767:
    print >>sys.stderr, "Error: more than 32767 stops found - need to fix file format!"
    sys.exit(1)

tree=kdtree(stops)

def recordnumgenerator():
    num=0
    while 1:
        yield num
        num+=1

# Header - 8 bytes - 'bus2', integer root pos
treeFile = file(sys.argv[1] + ".kdt", "wb")
treeFile.write(struct.pack(">4s", 'bus2'))
treeFile.seek(8,os.SEEK_SET)

metadataFile = file(sys.argv[1] + ".met", "wb")

# Write the tree
recordnumgen=recordnumgenerator()
rootpos=tree.write(treeFile,metadataFile,recordnumgen)

# output file headers and close 'em
treeFile.seek(4,os.SEEK_SET)
treeFile.write(struct.pack('>i',rootpos))
treeFile.close()
metadataFile.close()

# output the services - 'bus2', integer number of services
servicesFile = file(sys.argv[1] + ".srv", "wb")
servicesFile.write(struct.pack('>i', len(servicesList)));
for service in servicesList:
    servicesFile.write(service['ServiceName'])
    servicesFile.write("\0")
servicesFile.close();
